name: kinase-conformational-modeling
channels:
  - conda-forge
  - openeye
  - tpeulen
dependencies:
  - python==3.7
  - appdirs
  - biopandas
  - biopython
  - bravado
  - jupyterlab
  - matplotlib
  - mdanalysis
  - mdtraj
  - nglview
  - numpy
  - openeye-toolkits
  - openforcefield
  - osfclient
  - openmm
  - openmmtools
  - pandas
  - pymol-open-source
  - requests
  - rdkit
  - tqdm
  - pip:
    - https://github.com/volkamerlab/opencadd/archive/3fe042334c17368deaa17794e5368a632f964e3a.zip
    - https://github.com/openkinome/kinoml/archive/64681ca476ffe647ec55d5fb1cb122707815e07f.zip