name: kinase-conformational-modeling
channels:
  - conda-forge
  - openeye
  - tpeulen
dependencies:
  - python==3.7
  - appdirs
  - biopandas
  - biopython
  - bravado
  - jupyterlab
  - matplotlib
  - mdanalysis
  - nglview
  - numpy
  - openeye-toolkits
  - openforcefield
  - osfclient
  - pandas
  - pymol-open-source
  - requests
  - rdkit
  - tqdm
  - pip:
    - https://github.com/volkamerlab/opencadd/archive/3fe042334c17368deaa17794e5368a632f964e3a.zip
    - https://github.com/openkinome/kinoml/archive/550e902037a62c120f71a83dd04f95e2ad408666.zip